<a href="https://colab.research.google.com/github/WhoAreYou1224/datavis2025/blob/main/Copy_of_midterm2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ให้สืบหาฆาตรกร (10 คะแนน) และ ผู้บงการ (5 คะแนน) ในคดี ฆาตรกรรม (murder) ที่เกิดขึ้นในวันที่ 15 มกราคม 2018 ที่เมือง Pandas City โดยเริ่มจากการตรวจสอบ ข้อมูลคดีในไฟล์ crime_scene_report.csv

In [50]:
import pandas

In [51]:
import pandas as pd

In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [57]:
 crimescenereportdf

,date,type,description,city
0,1970-01-01 00:00:00.020180115,robbery,A Man Dressed as Spider-Man Is on a Robbery Spree,NYC
1,1970-01-01 00:00:00.020180115,murder,Life? Dont talk to me about life.,Albany
2,1970-01-01 00:00:00.020180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
3,1970-01-01 00:00:00.020180215,murder,REDACTED REDACTED REDACTED,Pandas City
4,1970-01-01 00:00:00.020180215,murder,Someone killed the guard! He took an arrow to ...,Pandas City
...,...,...,...,...
1223,1970-01-01 00:00:00.020180430,bribery,\n,Garden Grove
1224,1970-01-01 00:00:00.020180430,fraud,‘Why not?’ said the March Hare.\n,Houma
1225,1970-01-01 00:00:00.020180430,assault,\n,Fontana
1226,1970-01-01 00:00:00.020180501,assault,be NO mistake about it: it was neither more no...,Trenton
1227,1970-01-01 00:00:00.020180115,murder,Security footage shows that there were 2 witne...,Pandas City

In [61]:
crime_details = crimescenereportdf[
    (crimescenereportdf['date'] == '1970-01-01 00:00:00.020180115') &
    (crimescenereportdf['city'] == 'Pandas City') &
    (crimescenereportdf['type'] == 'murder')
]
display(crime_details)

,date,type,description,city
1227,1970-01-01 00:00:00.020180115,murder,Security footage shows that there were 2 witne...,Pandas City

In [64]:
# แสดงรายละเอียดของคดี
if not crime_details.empty:
    print("\nรายละเอียดของคดีฆาตกรรม:")
    print(crime_details)

รายละเอียดของคดีฆาตกรรม:
                              date    type  \
1227 1970-01-01 00:00:00.020180115  murder

                                            description         city
1227  Security footage shows that there were 2 witne...  Pandas City

In [65]:
if not crime_details.empty:
    clue = crime_details['description'].iloc[0]
    print(f"\nเบาะแสจากที่เกิดเหตุ: {clue}")

เบาะแสจากที่เกิดเหตุ: Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".

In [68]:
interview = pd.read_csv('/content/drive/MyDrive/data midterm/interview.csv')
person = pd.read_csv('/content/drive/MyDrive/data midterm/person.csv')
print("ไฟล์ interview.csv และ person.csv โหลดสำเร็จแล้ว")

ไฟล์ interview.csv และ person.csv โหลดสำเร็จแล้ว

In [70]:

# กรองหาคำให้การที่มีเบาะแสเกี่ยวกับคดีฆาตกรรม
# เราสามารถใช้คำสำคัญจากรายงานคดีหรือตรวจสอบเบาะแสที่เกี่ยวข้อง
witness_interview = interview[
    interview['transcript'].str.contains('gunshot') &
    interview['transcript'].str.contains('Get Fit Now Gym')
]

In [71]:
if not witness_interview.empty:
    print("\nคำให้การของพยานที่เกี่ยวข้อง:")
    print(witness_interview)

    # ดึง person_id ของพยาน
    witness_ids = witness_interview['person_id'].tolist()
    print(f"\nรหัสประจำตัวของพยาน: {witness_ids}")

    # ค้นหาข้อมูลของพยานจากไฟล์ person.csv
    witness_info = person[person['id'].isin(witness_ids)]
    print("\nข้อมูลพยาน:")
    print(witness_info)

คำให้การของพยานที่เกี่ยวข้อง:
      person_id                                         transcript
4988      14887  I heard a gunshot and then saw a man run out. ...

รหัสประจำตัวของพยาน: [14887]

ข้อมูลพยาน:
        id            name  license_id  address_number address_street_name  \
499  14887  Morty Schapiro      118009            4919     Northwestern Dr

           ssn
499  111564949

In [73]:
get_fit_now_member = pd.read_csv('/content/drive/MyDrive/data midterm/get_fit_now_member.csv')
drivers_license = pd.read_csv('/content/drive/MyDrive/data midterm/drivers_license.csv')
print("ไฟล์ get_fit_now_member.csv และ drivers_license.csv โหลดสำเร็จแล้ว")

ไฟล์ get_fit_now_member.csv และ drivers_license.csv โหลดสำเร็จแล้ว

In [74]:
# กรองหาสมาชิก Get Fit Now ที่มีรหัสขึ้นต้นด้วย '48Z' และเป็นสมาชิกแบบ 'gold'
suspect_gym = get_fit_now_member[
    (get_fit_now_member['id'].str.startswith('48Z')) &
    (get_fit_now_member['membership_status'] == 'gold')
]

In [75]:
print("\nผู้ต้องสงสัยจากข้อมูลสมาชิกยิม:")
print(suspect_gym)

ผู้ต้องสงสัยจากข้อมูลสมาชิกยิม:
        id  person_id           name  membership_start_date membership_status
181  48Z7A      28819   Joe Germuska               20160305              gold
182  48Z55      67318  Jeremy Bowers               20160101              gold

In [79]:
suspect_car = drivers_license[
    drivers_license['plate_number'].str.contains('H42W')
]

In [81]:
print("\nผู้ต้องสงสัยจากข้อมูลป้ายทะเบียนรถ:")
print(suspect_car)

ผู้ต้องสงสัยจากข้อมูลป้ายทะเบียนรถ:
          id  age  height eye_color hair_color  gender plate_number  \
915   183779   21      65      blue     blonde  female       H42W0X
3529  423327   30      70     brown      brown    male       0H42W2
6240  664760   21      71     black      black    male       4H42WR

       car_make car_model
915      Toyota     Prius
3529  Chevrolet  Spark LS
6240     Nissan    Altima

In [83]:
# รวมข้อมูลเพื่อระบุตัวตนผู้ต้องสงสัย
# เราจะรวมข้อมูลจาก person.csv กับข้อมูลใบขับขี่ของผู้ต้องสงสัย
person_from_car = pd.merge(suspect_car, person, left_on='id', right_on='license_id')
display(person_from_car)

,id_x,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model,id_y,name,license_id,address_number,address_street_name,ssn
0,183779,21,65,blue,blonde,female,H42W0X,Toyota,Prius,78193,Maxine Whitely,183779,110,Fisk Rd,137882671
1,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279
2,664760,21,71,black,black,male,4H42WR,Nissan,Altima,51739,Tushar Chandra,664760,312,Phi St,137882671

In [94]:
# จากนั้นรวมข้อมูลของคนที่มีทั้งป้ายทะเบียนรถและเป็นสมาชิกยิม
murderer_suspect = pd.merge(person_from_car, suspect_gym, left_on='id_y', right_on='person_id')

if not murderer_suspect.empty:
    print("\nข้อมูลผู้ต้องสงสัยฆาตกร:")
    print(murderer_suspect)
    murderer_name = murderer_suspect['name_y'].iloc[0]
    print(f"\nฆาตกรน่าจะเป็น: {murderer_name}")

ข้อมูลผู้ต้องสงสัยฆาตกร:
     id_x  age  height eye_color hair_color gender plate_number   car_make  \
0  423327   30      70     brown      brown   male       0H42W2  Chevrolet

  car_model   id_y         name_x  license_id  address_number  \
0  Spark LS  67318  Jeremy Bowers      423327             530

     address_street_name        ssn     id  person_id         name_y  \
0  Washington Pl, Apt 3A  871539279  48Z55      67318  Jeremy Bowers

   membership_start_date membership_status
0               20160101              gold

ฆาตกรน่าจะเป็น: Jeremy Bowers

##ฆาตกรน่าจะเป็น: Jeremy Bowers

#**หาตัวผู้บงการ**

In [149]:
import pandas as pd

try:
    person = pd.read_csv('/content/drive/MyDrive/data midterm/person.csv')
    drivers_license = pd.read_csv('/content/drive/MyDrive/data midterm/drivers_license.csv')
    print("โหลดไฟล์ข้อมูลสำเร็จแล้ว")
except FileNotFoundError:
    print("ไม่พบไฟล์ที่จำเป็น กรุณาตรวจสอบว่าอัปโหลดไฟล์ครบถ้วนแล้ว")

โหลดไฟล์ข้อมูลสำเร็จแล้ว

In [150]:
# ค้นหาบุคคลที่มีที่อยู่บนถนน Northwestern Dr
suspect_person = person[
    (person['address_street_name'] == 'Northwestern Dr')
]

if not suspect_person.empty:
    print("\nผู้ต้องสงสัยจากที่อยู่:")
    print(suspect_person)

ผู้ต้องสงสัยจากที่อยู่:
         id                  name  license_id  address_number  \
2     10010             Muoi Cary      385336             741
282   12711        Norman Apolito      667757             599
499   14887        Morty Schapiro      118009            4919
528   15171          Weldon Penso      336999             311
811   17729        Lasonya Wildey      439686            3824
904   18376              Josh Shi      653712            1091
1021  19420           Cody Schiel      890431            3524
1338  22239         Dusty Sigafus      710517            1125
1426  23044          Val Portlock      924989            3143
1522  23960  Kristopher Lagerberg      658777            1392
1686  25615         Olevia Morena      388477             812
1812  26758      Angelena Billman      942074             629
1981  28360        Rashad Cascone      924517            3212
2131  29608       Willetta Lurvey      800568            1028
2535  33415         Homer Simpson      108392             981
2620  34155      Allyson Lazenson      814209            2840
2635  34352    Vincenza Burkhardt      436470            2512
2871  36378        Freddie Ellzey      267882            3449
3237  39688            Abe Roeker      537445             689
3316  40336       Fredia Billeter      251082             404
3368  40760          Renata Faver      976650             745
3743  44004           Alison Eska      327797            2951
3795  44542        Ivory Mcgrevey      873842             897
4595  51114     Christena Saffell      814284            3055
4643  51552           Bonita Knie      764124            1726
4806  53076           Boris Bijou      664914            3327
4871  53699      Christian Pagano      628433            2585
4886  53890        Sophie Tiberio      957671            3755
4956  54564         Sammie Sengun      217286            2590
5024  55130        Shiloh Huntoon      472118             951
5450  59307          Cyril Yongue      753524            2903
6476  68690            Yer Modest      852404            3046
6698  70485     Andera Kostelecky      354822            1252
6865  71924        Laurie Scronce      774116            1418
6877  72076     Courtney Bordeaux      324614            1707
7040  73368        Torie Thalmann      773862            3697
7296  75484          Del Tacderen      447887             607
7888  80921       Donovan Yackley      222395            2386
7902  81052     Calvin Czelusniak      471483            1516
7993  81885         Kurtis Masuda      934201            2108
8369  85280             Donn Duin      569122             540
8608  87456   Leonora Wolfsberger      215868            3483
8720  88423           Teri Ehrich      510876            1879
8888  89906       Kinsey Erickson      510019             309
8939  90397     Dionna Kranwinkle      797260            2678
9272  93509        Emmitt Aceuedo      916706            3491
9569  96178           Galina Khuu      450248            2183
9609  96595         Coretta Cubie      303645            3631
9841  98593           Jonah Toner      578982            2947
9991  99826          Ivy Kazarian      994470             892

     address_street_name        ssn
2        Northwestern Dr  828638512
282      Northwestern Dr  778264744
499      Northwestern Dr  111564949
528      Northwestern Dr  131379495
811      Northwestern Dr  917817122
904      Northwestern Dr  193899001
1021     Northwestern Dr  947110049
1338     Northwestern Dr  724386723
1426     Northwestern Dr  100593316
1522     Northwestern Dr  492912529
1686     Northwestern Dr  962831331
1812     Northwestern Dr  341854756
1981     Northwestern Dr  838907424
2131     Northwestern Dr  843751378
2535     Northwestern Dr  871392019
2620     Northwestern Dr  991150469
2635     Northwestern Dr  197913046
2871     Northwestern Dr  474117596
3237     Northwestern Dr  438969447
3316     Northwestern Dr  108056488
3368     Northwestern Dr  547572040
3743     Northwestern Dr  306417867
3795     Northwestern Dr  988557407
4595     Northwestern Dr  247657547
4643     Northwestern Dr  597137908
4806     Northwestern Dr  401191868
4871     Northwestern Dr  644772304
4886     Northwestern Dr  442830147
4956     Northwestern Dr  848854310
5024     Northwestern Dr  826647644
5450     Northwestern Dr  866057839
6476     Northwestern Dr  419238039
6698     Northwestern Dr  787423012
6865     Northwestern Dr  254883636
6877     Northwestern Dr  347966356
7040     Northwestern Dr  341559436
7296     Northwestern Dr  243821337
7888     Northwestern Dr  515049359
7902     Northwestern Dr  657531837
7993     Northwestern Dr  201272595
8369     Northwestern Dr  613873810
8608     Northwestern Dr  565203106
8720     Northwestern Dr  248637345
8888     Northwestern Dr  635287661
8939     Northwestern Dr  278964807
9272     Northwestern Dr  979073160
9569     Northwestern Dr  398518185
9609     Northwestern Dr  378403829
9841     Northwestern Dr  745853548
9991     Northwestern Dr  208359813

In [152]:
# รวมข้อมูลกับไฟล์ drivers_license เพื่อยืนยันลักษณะของผู้บงการ
mastermind_suspect = pd.merge(
    suspect_person,
    drivers_license,
    left_on='license_id',
    right_on='id'
)
display(mastermind_suspect)

,id_x,name,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,10010,Muoi Cary,385336,741,Northwestern Dr,828638512,385336,24,79,blue,green,female,GM6Y5J,Mercedes-Benz,CLS-Class
1,12711,Norman Apolito,667757,599,Northwestern Dr,778264744,667757,19,58,green,blonde,male,56018Z,Mazda,CX-5
2,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949,118009,64,84,blue,white,male,00NU00,Mercedes-Benz,E-Class
3,15171,Weldon Penso,336999,311,Northwestern Dr,131379495,336999,76,72,amber,blonde,male,8X1B67,Nissan,Versa
4,17729,Lasonya Wildey,439686,3824,Northwestern Dr,917817122,439686,30,55,brown,black,female,31U45U,Mitsubishi,Pajero
5,19420,Cody Schiel,890431,3524,Northwestern Dr,947110049,890431,77,52,amber,white,male,AZZA24,Lincoln,LS
6,22239,Dusty Sigafus,710517,1125,Northwestern Dr,724386723,710517,34,61,black,red,female,W8CONV,GMC,Sierra 2500
7,23044,Val Portlock,924989,3143,Northwestern Dr,100593316,924989,32,69,brown,blue,male,D5YH6U,Suzuki,Aerio
8,23960,Kristopher Lagerberg,658777,1392,Northwestern Dr,492912529,658777,30,70,blue,brown,male,F615HM,Maybach,57
9,25615,Olevia Morena,388477,812,Northwestern Dr,962831331,388477,88,50,brown,black,female,0LSD76,Mercedes-Benz,CLS-Class
10,26758,Angelena Billman,942074,629,Northwestern Dr,341854756,942074,78,78,brown,blonde,female,Z6ADM1,Ford,Mustang
11,28360,Rashad Cascone,924517,3212,Northwestern Dr,838907424,924517,34,56,amber,brown,male,38F873,Isuzu,Axiom
12,29608,Willetta Lurvey,800568,1028,Northwestern Dr,843751378,800568,83,75,amber,white,female,HK7UB5,GMC,Savana 3500
13,34155,Allyson Lazenson,814209,2840,Northwestern Dr,991150469,814209,61,71,blue,blonde,female,Q02C3F,Mercedes-Benz,C-Class
14,34352,Vincenza Burkhardt,436470,2512,Northwestern Dr,197913046,436470,27,57,black,grey,female,4QJJ72,Mercury,Grand Marquis
15,36378,Freddie Ellzey,267882,3449,Northwestern Dr,474117596,267882,68,58,green,blue,male,CIU254,Scion,xB
16,39688,Abe Roeker,537445,689,Northwestern Dr,438969447,537445,20,71,blue,black,male,GNUT3J,Dodge,Grand Caravan
17,40336,Fredia Billeter,251082,404,Northwestern Dr,108056488,251082,31,55,blue,black,female,56254O,Cadillac,STS
18,40760,Renata Faver,976650,745,Northwestern Dr,547572040,976650,29,79,blue,blonde,female,3073O2,Dodge,Caravan
19,44004,Alison Eska,327797,2951,Northwestern Dr,306417867,327797,63,52,black,black,female,GGBK66,BMW,M3
20,44542,Ivory Mcgrevey,873842,897,Northwestern Dr,988557407,873842,31,63,brown,blue,male,IB8715,Mazda,RX-8
21,51114,Christena Saffell,814284,3055,Northwestern Dr,247657547,814284,82,71,green,blonde,female,3E2S72,Ford,Taurus
22,51552,Bonita Knie,764124,1726,Northwestern Dr,597137908,764124,46,78,amber,blonde,female,1I281J,Chrysler,Town & Country
23,53076,Boris Bijou,664914,3327,Northwestern Dr,401191868,664914,54,60,amber,grey,male,680KGQ,Mercury,Monterey
24,53699,Christian Pagano,628433,2585,Northwestern Dr,644772304,628433,43,82,green,black,male,3VIYZQ,Chrysler,Sebring
25,53890,Sophie Tiberio,957671,3755,Northwestern Dr,442830147,957671,35,73,amber,grey,female,U05L07,Volvo,S90
26,54564,Sammie Sengun,217286,2590,Northwestern Dr,848854310,217286,69,57,black,brown,male,M581U7,Ford,Mustang
27,55130,Shiloh Huntoon,472118,951,Northwestern Dr,826647644,472118,34,54,black,grey,female,AG4YGG,Ford,Escape
28,59307,Cyril Yongue,753524,2903,Northwestern Dr,866057839,753524,89,77,brown,grey,male,6YA5LT,Maybach,Landaulet
29,68690,Yer Modest,852404,3046,Northwestern Dr,419238039,852404,29,79,green,grey,female,366FO2,Bentley,Continental
30,70485,Andera Kostelecky,354822,1252,Northwestern Dr,787423012,354822,49,75,blue,black,female,2W4H5X,Mazda,B-Series
31,71924,Laurie Scronce,774116,1418,Northwestern Dr,254883636,774116,88,53,green,red,female,Z67X8S,Chevrolet,Silverado 3500
32,72076,Courtney Bordeaux,324614,1707,Northwestern Dr,347966356,324614,24,70,amber,white,male,U181XV,Mercury,Monterey
33,73368,Torie Thalmann,773862,3697,Northwestern Dr,341559436,773862,32,73,green,red,female,JY25MA,GMC,Yukon XL 2500
34,75484,Del Tacderen,447887,607,Northwestern Dr,243821337,447887,37,62,blue,white,male,Z76OJY,BMW,5 Series
35,80921,Donovan Yackley,222395,2386,Northwestern Dr,515049359,222395,59,57,black,blonde,male,64A257,Kia,Rio
36,81052,Calvin Czelusniak,471483,1516,Northwestern Dr,657531837,471483,36,81,blue,white,male,P8NC1C,Cadillac,Escalade
37,81885,Kurtis Masuda,934201,2108,Northwestern Dr,201272595,934201,35,64,blue,grey,male,INRZQ2,GMC,Sierra 3500
38,85280,Donn Duin,569122,540,Northwestern Dr,613873810,569122,60,54,black,red,male,5A7ZUI,BMW,530
39,87456,Leonora Wolfsberger,215868,3483,Northwestern Dr,565203106,215868,43,80,blue,blue,female,43X3A5,Cadillac,Escalade
40,88423,Teri Ehrich,510876,1879,Northwestern Dr,248637345,510876,84,81,green,white,female,W8LCSC,Chevrolet,Blazer
41,90397,Dionna Kranwinkle,797260,2678,Northwestern Dr,278964807,797260,87,82,black,white,female,86FJ55,Mazda,RX-8
42,93509,Emmitt Aceuedo,916706,3491,Northwestern Dr,979073160,916706,83,61,brown,blonde,male,1BUUJ2,Infiniti,Q
43,96178,Galina Khuu,450248,2183,Northwestern Dr,398518185,450248,78,65,green,green,female,C4A46I,BMW,X6
44,96595,Coretta Cubie,303645,3631,Northwestern Dr,378403829,303645,35,80,black,blonde,female,2Y40MP,Lexus,GS
45,98593,Jonah Toner,578982,2947,Northwestern Dr,745853548,578982,28,78,black,blonde,male,3COUC4,Chrysler,Town & Country
46,99826,Ivy Kazarian,994470,892,Northwestern Dr,208359813,994470,84,53,amber,blue,female,K316N0,Aston Martin,V8 Vantage S

In [161]:
if not mastermind_suspect.empty:
    # กรองหาผู้หญิงผมสีแดง
    the_mastermind = mastermind_suspect[
        (mastermind_suspect['gender'] == 'female') &
        (mastermind_suspect['hair_color'] == 'red')
    ]

    if not the_mastermind.empty:
        mastermind_name = the_mastermind['name'].iloc[0] # Corrected from 'name_x' to 'name'
        print("\nข้อมูลผู้บงการ:")
        print(the_mastermind)
        print(f"\nผู้บงการในคดีนี้คือ: {mastermind_name}")

ข้อมูลผู้บงการ:
     id_x            name  license_id  address_number address_street_name  \
6   22239   Dusty Sigafus      710517            1125     Northwestern Dr
31  71924  Laurie Scronce      774116            1418     Northwestern Dr
33  73368  Torie Thalmann      773862            3697     Northwestern Dr

          ssn    id_y  age  height eye_color hair_color  gender plate_number  \
6   724386723  710517   34      61     black        red  female       W8CONV
31  254883636  774116   88      53     green        red  female       Z67X8S
33  341559436  773862   32      73     green        red  female       JY25MA

     car_make       car_model
6         GMC     Sierra 2500
31  Chevrolet  Silverado 3500
33        GMC   Yukon XL 2500

ผู้บงการในคดีนี้คือ: Dusty Sigafus

##ผู้บงการในคดีนี้คือ: Dusty Sigafus

##